apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pro-jection.fullname" . }}-storage
  labels:
    {{- include "pro-jection.labels" . | nindent 4 }}
data:
  storage.yaml: |
    scheme: fs
    root: {{ .Values.storage.mountPath | quote }}
